/**
  ******************************************************************************
  * @file    mx.c
  * @author  SRA - GPM
  *
  *
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "spi.h"
#include "i2c.h"
#include "mdf.h"
#include "adc.h"
#include "gpdma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"
#include "usb_otg.h"


/**
  * (USER_BUTTON) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_UBInitParams =
{
  MX_GPIO_PE0_Init,
  USR_BUTTON_EXTI_IRQn,
  USR_BUTTON_Pin,
  USR_BUTTON_GPIO_Port
};

/**
  * (LED1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED1InitParams =
{
  MX_GPIO_PH12_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED1_Pin,
  LED1_GPIO_Port
};

/**
  * (LED2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED2InitParams =
{
  MX_GPIO_PH10_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED2_Pin,
  LED2_GPIO_Port
};

/**
  * (INT_EX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT_EXInitParams =
{
  MX_GPIO_PG6_Init,
  INT_EX_EXTI_IRQn,
  INT_EX_Pin,
  INT_EX_GPIO_Port
};

/**
  * (INT2_EX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_EXInitParams =
{
  MX_GPIO_PB1_Init,
  EXTI1_IRQn,
  GPIO_PIN_1,
  GPIOB
};

/**
  * (INT_STT) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT_STTInitParams =
{
  MX_GPIO_PF5_Init,
  INT_STT_EXTI_IRQn,
  INT_STT_Pin,
  INT_STT_GPIO_Port
};

/**
  * (INT_MAG) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT_MAGInitParams =
{
  MX_GPIO_PF9_Init,
  INT_MAG_EXTI_IRQn,
  INT_MAG_Pin,
  INT_MAG_GPIO_Port
};

/**
  * (INT1_ICLX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_ICLXInitParams =
{
  MX_GPIO_PF3_Init,
  INT1_ICLX_EXTI_IRQn,
  INT1_ICLX_Pin,
  INT1_ICLX_GPIO_Port
};

/**
  * (INT2_DLPC) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_DLPCInitParams =
{
  MX_GPIO_PF2_Init,
  INT2_DLPC_EXTI_IRQn,
  INT2_DLPC_Pin,
  INT2_DLPC_GPIO_Port
};

/**
  * (INT1_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DHCXInitParams =
{
  MX_GPIO_PB8_Init,
  INT1_DHCX_EXTI_IRQn,
  INT1_DHCX_Pin,
  INT1_DHCX_GPIO_Port
};

/**
  * (INT2_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_DHCXInitParams =
{
  MX_GPIO_PF4_Init,
  INT2_DHCX_EXTI_IRQn,
  INT2_DHCX_Pin,
  INT2_DHCX_GPIO_Port
};

/**
  * (INT1_DWB) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DWBInitParams =
{
  MX_GPIO_PF15_Init,
  INT1_DWB_EXTI_IRQn,
  INT1_DWB_Pin,
  INT1_DWB_GPIO_Port
};

/**
  * (INT1_EXTERNAL_DWB) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_EXTERNAL_DWBInitParams =
{
  MX_GPIO_PG6_Init,
  INT_EX_EXTI_IRQn,
  INT_EX_Pin,
  INT_EX_GPIO_Port
};

/**
  * (INT1_EXTERNAL_ISPU) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_EXTERNAL_ISPUInitParams =
{
  MX_GPIO_PG6_Init,
  INT_EX_EXTI_IRQn,
  INT_EX_Pin,
  INT_EX_GPIO_Port
};

/**
  * PI7 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_ICLXInitParams =
{
  MX_GPIO_PI7_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CS_ICLX_Pin,
  CS_ICLX_GPIO_Port
};

/**
  * PH6 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_DLPCInitParams =
{
  MX_GPIO_PH6_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CS_DLPC_Pin,
  CS_DLPC_GPIO_Port
};

/**
  * PH15 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_DHCXInitParams =
{
  MX_GPIO_PH15_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CS_DHCX_Pin,
  CS_DHCX_GPIO_Port
};

/**
  * PF12 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_DWBInitParams =
{
  MX_GPIO_PF12_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CS_DWB_Pin,
  CS_DWB_GPIO_Port
};

/**
  * PI0 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_EXTERNALInitParams =
{
  MX_GPIO_PI0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  EX_SPI_NSS_Pin,
  EX_SPI_NSS_GPIO_Port
};

/**
  * PA8 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PA8InitParams =
{
  MX_GPIO_PA8_Init,
  UsageFault_IRQn, /*!< NOT USED */
  SW_SEL_Pin,
  SW_SEL_GPIO_Port
};

/**
  * PA0 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PA0InitParams =
{
  MX_GPIO_PA0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CHRG_Pin,
  CHRG_GPIO_Port
};

/**
  * PD0 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PD0InitParams =
{
  MX_GPIO_PD0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  C_EN_Pin,
  C_EN_GPIO_Port
};

/**
  * PE7 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_MXCHIP_NOTIFYInitParams =
{
  MX_GPIO_PE7_Init,
  EXTI7_IRQn,
  GPIO_PIN_7,
  GPIOE
};

/**
  * PH7 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_MXCHIP_NSSInitParams =
{
  MX_GPIO_PH7_Init,
  UsageFault_IRQn, /*!< NOT USED */
  GPIO_PIN_7,
  GPIOH
};

/**
  * PE12 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_MXCHIP_RESETInitParams =
{
  MX_GPIO_PE12_Init,
  UsageFault_IRQn, /*!< NOT USED */
  GPIO_PIN_12,
  GPIOE
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_FS,
  .p_mx_init_f = MX_USB_OTG_FS_PCD_Init,
  .irq_n = OTG_FS_IRQn
};

/**
  * SPI2 initialization parameters.
  */
const MX_SPIParams_t MX_SPI2InitParams =
{
  .p_mx_init_f = MX_SPI2_Init,
  .p_spi_handle = &hspi2,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_dma_rx_irq_n = GPDMA1_Channel0_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel1_IRQn
};

/**
  * I2C2 initialization parameters.
  */
const MX_I2CParams_t MX_I2C2InitParams =
{
  .p_mx_init_f = MX_I2C2_Init,
  .p_i2c_handle = &hi2c2,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i2c_er_irq_n = I2C2_ER_IRQn,
  .i2c_ev_irq_n = I2C2_EV_IRQn,
  .i2c_dma_rx_irq_n = GPDMA1_Channel2_IRQn,
  .i2c_dma_tx_irq_n = GPDMA1_Channel3_IRQn
};

/**
  * I2C3 initialization parameters.
  */
const MX_I2CParams_t MX_I2C3InitParams =
{
  .p_mx_init_f = MX_I2C3_Init,
  .p_i2c_handle = &hi2c3,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i2c_er_irq_n = I2C3_ER_IRQn,
  .i2c_ev_irq_n = I2C3_EV_IRQn,
  .i2c_dma_rx_irq_n = GPDMA1_Channel6_IRQn,
  .i2c_dma_tx_irq_n = GPDMA1_Channel7_IRQn
};

/**
  * MDF initialization parameters.
  */
const MX_MDFParams_t MX_MDF1InitParams =
{
  .p_mdf_config = &MdfFilterConfig0,
  .p_mdf = &MdfHandle0,
  .p_mdf_dma_config = &MdfDmaConfig,
  .irq_n = GPDMA1_Channel4_IRQn,
  .p_mx_init_f = MX_MDF1_Init,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom
};

/**
  * ADF initialization parameters.
  */
const MX_MDFParams_t MX_ADF1InitParams =
{
  .p_mdf_config = &AdfFilterConfig0,
  .p_mdf = &AdfHandle0,
  .p_mdf_dma_config = &AdfDmaConfig,
  .irq_n = GPDMA1_Channel5_IRQn,
  .p_mx_init_f = MX_ADF1_Init,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom
};

/**
  * ADC1 initialization parameters.
  */
const MX_ADCParams_t MX_ADC1InitParams =
{
  .p_adc = &hadc1,
  .p_mx_init_f = MX_ADC1_Init
};

/**
  * ADC4 initialization parameters.
  */
const MX_ADCParams_t MX_ADC4InitParams =
{
  .p_adc = &hadc4,
  .p_mx_init_f = MX_ADC4_Init
};

/**
  * TIM3 initialization parameters.
  */
const MX_TIMParams_t MX_TIM3InitParams =
{
  .p_mx_init_f = MX_TIM3_Init,
  .p_tim = &htim3,
  .irq_n = TIM3_IRQn
};

/**
  * TIM4 initialization parameters.
  */
const MX_TIMParams_t MX_TIM4InitParams =
{
  .p_mx_init_f = MX_TIM4_Init,
  .p_tim = &htim4,
  .irq_n = TIM4_IRQn
};

/**
  * TIM5 initialization parameters.
  */
const MX_TIMParams_t MX_TIM5InitParams =
{
  .p_mx_init_f = MX_TIM5_Init,
  .p_tim = &htim5,
  .irq_n = TIM5_IRQn
};
