/**
  ******************************************************************************
  * @file    I3CMasterDriver.h
  * @author  SRA - MCD
  * @brief   I3C driver: master DMA
  *
  * Driver for the I3C in master mode. Communication on the bus is done in
  * DMA mode.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file in
  * the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  *
  ******************************************************************************
  */
#ifndef INCLUDE_DRIVERS_I3CMASTERDRIVER_H_
#define INCLUDE_DRIVERS_I3CMASTERDRIVER_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "drivers/IIODriver.h"
#include "drivers/IDriver_vtbl.h"
#include "drivers/IIODriver_vtbl.h"
#include "mx.h"
#include "tx_api.h"


/* driver error code */
/*********************/

#ifndef SYS_NO_ERROR_CODE
#define SYS_NO_ERROR_CODE                                 0
#endif
#ifndef SYS_BASE_I3C_M_ERROR_CODE
#define SYS_BASE_I3C_M_ERROR_CODE                         1
#endif
#define SYS_I3C_M_WRITE_READ_ERROR_CODE                   SYS_BASE_I3C_M_ERROR_CODE + 1
#define SYS_I3C_M_WRITE_ERROR_CODE                        SYS_BASE_I3C_M_ERROR_CODE + 2
#define SYS_I3C_M_READ_ERROR_CODE                         SYS_BASE_I3C_M_ERROR_CODE + 3


/**
  * Create  type name for _I3CMasterDriver_t.
  */
typedef struct _I3CMasterDriver_t I3CMasterDriver_t;

/**
  * Initialization parameters for the driver.
  */
typedef struct _I3CMasterDriverParams_t
{
  /**
    * Specifies the peripheral HAL initialization parameters generated by CubeMX.
    */
  MX_I3CParams_t *p_mx_i3c_cfg;

  /**
    * Generic parameter.
    */
  uint32_t param;
} I3CMasterDriverParams_t;

/**
  *  I3CMasterDriver internal structure.
  */
struct _I3CMasterDriver_t
{
  /**
    * Base class object.
    */
  IIODriver super;

  /* Driver variables should be added here */

  /**
    * Specifies all the configuration parameters for the I3C peripheral linked to
    * an instance of this class. It based on the HAL driver generated by CubeMX.
    */
  I3CMasterDriverParams_t mx_handle;

  /**
    * Synchronization object used to synchronize the low lever driver with the task.
    */
  TX_SEMAPHORE sync_obj;

  /**
    * Specifies the address of the target device. All read and write operation are done with the device specified by this address.
    */
  uint16_t target_device_addr;

  /**
    * Register address size in bytes used for private transfers (1 or 2).
    */
  uint8_t reg_addr_size;

  /**
    * Flag used to check if the driver is already initialized. It is used to avoid to initialize the same driver more than once.
    */
  boolean_t is_initialized;
};


/* Public API declaration */
/**************************/

/**
  * Allocate an instance of I3CMasterDriver. The driver is allocated
  * in the FreeRTOS heap.
  *
  * @return a pointer to the generic interface ::IDriver if success,
  * or SYS_OUT_OF_MEMORY_ERROR_CODE otherwise.
  */
IIODriver *I3CMasterDriverAlloc(void);

/**
  * Send one byte register address in the I3C bus in blocking mode. This method is used
  * to implement the communication protocol adopted by the ST MEMS standard driver.
  *
  * @param _this [IN] specifies a pointer to a I3CMasterDriver object.
  * @param reg_addr [IN] specifies a register address in the target device.
  * @param timeout_ms [IN] specifies a timeout in ms. If the IO operation doesn't end before the timeout expire, then an error is generated.
  * @return SYS_NO_ERROR_CODE if success, an error code otherwise.
  */
sys_error_code_t I3CMasterDriverTransmitRegAddr(I3CMasterDriver_t *_this, I3C_XferTypeDef *contextBuffer,
                                                I3C_PrivateTypeDef *privateDescriptor, uint32_t timeout_ms);

/**
  * Set the address of a slave device in the I2C bus. All read and write operation are done with
  * the device specified by this address.
  *
  * @param _this [IN] specifies a pointer to a SPIMasterDriver object.
  * @param nAddress [IN] specifies address of the slave device in the I2C bus.
  * @return SYS_NO_ERROR_CODE
  */
sys_error_code_t I3CMasterDriverSetDeviceAddr(I3CMasterDriver_t *_this, uint16_t nAddress);

/**
  * Set register address size used by the next private transfers.
  *
  * @param _this [IN] specifies a pointer to a I3CMasterDriver object.
  * @param reg_addr_size [IN] register address size in bytes (1 or 2).
  * @return SYS_NO_ERROR_CODE if success, SYS_INVALID_PARAMETER_ERROR_CODE otherwise.
  */
sys_error_code_t I3CMasterDriverSetRegAddrSize(I3CMasterDriver_t *_this, uint8_t reg_addr_size);

/**
  * Execute I3C startup CCC sequence for a target and select the address used for private transfers.
  *
  * The sequence is:
  * 1) DISEC (broadcast, once per bus) to disable Hot-Join
  * 2) RSTDAA (broadcast, once per bus) to clear dynamic addresses
  * 3) SETDASA (direct, per target) when both static and dynamic address are provided
  *
  * @param _this [IN] specifies a pointer to a I3CMasterDriver object.
  * @param static_address [IN] target static address (7-bit).
  * @param dynamic_address [IN] desired target dynamic address (7-bit), 0 to skip SETDASA.
  * @return SYS_NO_ERROR_CODE if success, an error code otherwise.
  */
sys_error_code_t I3CMasterDriverConfigureTarget(I3CMasterDriver_t *_this, uint16_t static_address,
                                                uint16_t dynamic_address);


/* Inline functions definition */
/*******************************/

#ifdef __cplusplus
}
#endif

#endif /* INCLUDE_DRIVERS_I3CMASTERDRIVER_H_ */
