/**
 ******************************************************************************
 * @file    mx.c
 * @author  SRA - GPM
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
 */

#include "mx.h"
#include "spi.h"
#include "i2c.h"
#include "dfsdm.h"
#include "adc.h"
#include "dma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"
#include "usb_otg.h"

/**
  * (USER_BUTTON) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_UBInitParams =
{
  MX_GPIO_PE0_Init,
  USER_BUTTON_EXTI_IRQn,
  USER_BUTTON_Pin,
  USER_BUTTON_GPIO_Port
};

/**
  * (LED1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED1InitParams =
{
  MX_GPIO_PE1_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED1_Pin,
  LED1_GPIO_Port
};

/**
  * (LED2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED2InitParams =
{
  MX_GPIO_PD0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED2_Pin,
  LED2_GPIO_Port
};

/**
  * PF6 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PF6InitParams =
{
  MX_GPIO_PF6_Init,
  UsageFault_IRQn, /*!< NOT USED */
  STBC02_SW_SEL_Pin,
  STBC02_SW_SEL_GPIO_Port
};

/**
  * PF15 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PB0InitParams =
{
  MX_GPIO_PB0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  CHRGB0_Pin,
  CHRGB0_GPIO_Port
};

/**
  * PF8 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_PF8InitParams =
{
  MX_GPIO_PF8_Init,
  UsageFault_IRQn, /*!< NOT USED */
  C_EN_Pin,
  C_EN_GPIO_Port
};

/**
 * SPI3 initialization parameters.
 */
const MX_SPIParams_t MX_SPI3InitParams = {
    .p_mx_init_f = MX_SPI3_Init,
    .p_spi_handle  = &hspi3,
    .p_mx_dma_init_f = MX_DMA1_InitCustom,
    .spi_dma_rx_irq_n = DMA1_Channel1_IRQn,
    .spi_dma_tx_irq_n = DMA1_Channel2_IRQn
};

/**
 * I2C2 initialization parameters.
 */
const MX_I2CParams_t MX_I2C2InitParams = {
    .p_mx_init_f = MX_I2C2_Init,
    .p_i2c_handle = &hi2c2,
    .p_mx_dma_init_f = MX_DMA1_InitCustom,
    .i2c_er_irq_n = I2C2_ER_IRQn,
    .i2c_ev_irq_n = I2C2_EV_IRQn,
    .i2c_dma_rx_irq_n = DMA1_Channel3_IRQn,
    .i2c_dma_tx_irq_n = DMA1_Channel4_IRQn
};


/**
 * DFSDM initialization parameters.
 */
const MX_DFSDMParams_t MX_DFSDMCH5F0InitParams = {
  .p_dfsdm_channel = &hdfsdm1_channel5,
  .p_dfsdm_filter = &hdfsdm1_filter0,
  .p_dma = &hdma_dfsdm1_flt0,
  .irq_n = DMA1_Channel5_IRQn,
  .p_mx_init_f = MX_DFSDM1_Init,
  .p_mx_dma_init_f = MX_DMA1_InitCustom
};

/**
 * DFSDM initialization parameters.
 */
const MX_DFSDMParams_t MX_DFSDMCH0F1InitParams = {
  .p_dfsdm_channel = &hdfsdm1_channel0,
  .p_dfsdm_filter = &hdfsdm1_filter1,
  .p_dma = &hdma_dfsdm1_flt1,
  .irq_n = DMA1_Channel6_IRQn,
  .p_mx_init_f = MX_DFSDM1_Init,
  .p_mx_dma_init_f = MX_DMA1_InitCustom
};

/**
 * ADC1 initialization parameters.
 */
const MX_ADCParams_t MX_ADC1InitParams = {
    .p_adc = &hadc1,
    .p_mx_init_f = MX_ADC1_CustomInit
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_FS,
  .p_mx_init_f = MX_USB_OTG_FS_PCD_Init,
  .irq_n = OTG_FS_IRQn
};

/**
 * TIM3 initialization parameters.
 */
const MX_TIMParams_t MX_TIM3InitParams = {
    .p_mx_init_f = MX_TIM3_Init,
    .p_tim = &htim3,
    .irq_n = TIM3_IRQn
};

/**
 * TIM4 initialization parameters.
 */
const MX_TIMParams_t MX_TIM4InitParams = {
    .p_mx_init_f = MX_TIM4_Init,
    .p_tim = &htim4,
    .irq_n = TIM4_IRQn
};


/**
 * TIM5 initialization parameters.
 */
const MX_TIMParams_t MX_TIM5InitParams = {
    .p_mx_init_f = MX_TIM5_Init,
    .p_tim = &htim5,
    .irq_n = TIM5_IRQn
};

/**
 * TIM16 initialization parameters.
 */
const MX_TIMParams_t MX_TIM16InitParams = {
    .p_mx_init_f = MX_TIM16_Init,
    .p_tim = &htim16,
    .irq_n = TIM1_UP_TIM16_IRQn
};


/**
 * (CS_DWB) Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_CS_DWBInitParams = {
    MX_GPIO_PF5_Init,
    UsageFault_IRQn, /*!< NOT USED */
    CS_ADWB_Pin,
    CS_ADWB_GPIO_Port
};

/**
  * (INT1_DWB) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DWBInitParams = {
    MX_GPIO_PE14_Init,
    EXTI15_10_IRQn, /*!< NOT USED */
    INT1_ADWB_Pin,
    INT1_ADWB_GPIO_Port
};

/**
  * (INT_MAG) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT_MAGInitParams = {
    MX_GPIO_PF9_Init,
    EXTI9_5_IRQn, /*!< NOT USED */
    INT_M_Pin,
    INT_M_GPIO_Port
};

/**
  * (INT1_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DHCXInitParams = {
    MX_GPIO_PE8_Init,
    EXTI9_5_IRQn, /*!< NOT USED */
    INT1_DHC_Pin,
    INT1_DHC_GPIO_Port
};

/**
  * (INT2_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_DHCXInitParams = {
    MX_GPIO_PF4_Init,
    EXTI4_IRQn, /*!< NOT USED */
    INT2_DHC_Pin,
    INT2_DHC_GPIO_Port
};

/**
  * (CS_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_DHCXInitParams = {
    MX_GPIO_PF13_Init,
    UsageFault_IRQn, /*!< NOT USED */
    CS_DHC_Pin,
    CS_DHC_GPIO_Port
};

/**
  * (CS_DH) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_DHInitParams = {
    MX_GPIO_PD15_Init,
    UsageFault_IRQn, /*!< NOT USED */
    CS_DH_Pin,
    CS_DH_GPIO_Port
};

