/**
 ******************************************************************************
 * @file    mx.c
 * @author  SRA - GPM
 *
 * @date    Apr 9, 2021
 *
 * @brief Project peripherals configuration files.
 *
 * This files defines the peripherals configuration parameters that can be used
 * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
 * between the initialization code generated by CubeMX (see the .ioc file
 * in the tools folder) and the eLooM framework.
 *
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 ******************************************************************************
 */

#include "mx.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"
#include "spi.h"
#include "i2c.h"
#include "gpdma.h"
#include "usb_otg.h"
#include "mdf.h"

/**
  * SPI2 initialization parameters.
  */
const MX_SPIParams_t MX_SPI2InitParams =
{
  .p_mx_init_f = MX_SPI2_Init,
  .p_spi_handle = &hspi2,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_dma_rx_irq_n = GPDMA1_Channel0_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel1_IRQn
};

/**
 * I2C2 initialization parameters.
 */
const MX_I2CParams_t MX_I2C2InitParams =
{
  .p_mx_init_f = MX_I2C2_Init,
  .p_i2c_handle = &hi2c2,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i2c_er_irq_n = I2C2_ER_IRQn,
  .i2c_ev_irq_n = I2C2_EV_IRQn,
  .i2c_dma_rx_irq_n = GPDMA1_Channel2_IRQn,
  .i2c_dma_tx_irq_n = GPDMA1_Channel3_IRQn
};

/**
 * PE11 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PE11InitParams =
{
  MX_GPIO_PE11_Init,
  EXTI11_IRQn,
  GPIO_PIN_11,
  GPIOE
};

/**
 * PD10 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PD10InitParams =
{
  MX_GPIO_PD10_Init,
  EXTI10_IRQn,
  GPIO_PIN_10,
  GPIOD
};

/**
 * PG2 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PG2InitParams =
{
  MX_GPIO_PG2_Init,
  EXTI2_IRQn,
  GPIO_PIN_2,
  GPIOG
};

/**
 * TIM7 initialization parameters.
 */
const MX_TIMParams_t MX_TIM7InitParams =
{
  .p_mx_init_f = MX_TIM7_Init,
  .p_tim = &htim7,
  .irq_n = TIM7_IRQn
};

/**
 * PC13 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PC13InitParams =
{
  MX_GPIO_PC13_Init,
  EXTI13_IRQn,
  GPIO_PIN_13,
  GPIOC
};

/**
 * PH7 Initialization parameters.
 */
const MX_GPIOParams_t MX_GPIO_PH7InitParams =
{
  MX_GPIO_PH7_Init,
  UsageFault_IRQn, /*!< NOT USED */
  GPIO_PIN_7,
  GPIOH
};

/**
 * USB initialization parameters.
 */
const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_FS,
  .p_mx_init_f = MX_USB_OTG_FS_PCD_Init,
  .irq_n = OTG_FS_IRQn
};

/**
 * ADF initialization parameters.
 */
const MX_MDFParams_t MX_ADF1InitParams =
{
  .p_mdf_config = &AdfFilterConfig0,
  .p_mdf = &AdfHandle0,
  .p_mdf_dma_config = &AdfDmaConfig,
  .irq_n = GPDMA1_Channel5_IRQn,
  .p_mx_init_f = MX_ADF1_Init,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom
};

