/**
  ******************************************************************************
  * @file    mx.c
  * @author  STMicroelectronics - AIS - MCD Team
  * @version 3.0.1
  * @date    21/01/2022 10:35:14
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "tim.h"
#include "i2c.h"
#include "gpio.h"
#include "dma.h"
#include "usb_otg.h"


/**
  * TIM7 initialization parameters.
  */
const MX_TIMParams_t MX_TIM7InitParams =
{
  .p_mx_init_f = MX_TIM7_Init,
  .p_tim = &htim7,
  .irq_n = TIM7_IRQn
};

/**
  * I2C1 initialization parameters.
  */
const MX_I2CParams_t MX_I2C1InitParams =
{
  .p_mx_init_f = MX_I2C1_Init,
  .p_i2c_handle = &hi2c1,
  .p_mx_dma_init_f = MX_DMA_InitCustom,
  .i2c_er_irq_n = I2C1_ER_IRQn,
  .i2c_ev_irq_n = I2C1_EV_IRQn,
  .i2c_dma_rx_irq_n = DMA1_Stream0_IRQn,
  .i2c_dma_tx_irq_n = DMA1_Stream1_IRQn
};

/**
  * (USER_BUTTON) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_UBInitParams =
{
  MX_GPIO_PC13_Init,
  B1_EXTI_IRQn,
  B1_Pin,
  B1_GPIO_Port
};

/**
  * LED1 (Green) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD1InitParams =
{
  MX_GPIO_PB0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD1_Pin,
  LD1_GPIO_Port
};

/**
  * LED3 (Red) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD3InitParams =
{
  MX_GPIO_PB14_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD3_Pin,
  LD3_GPIO_Port
};

/**
  * LED2 (Yellow) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD2InitParams =
{
  MX_GPIO_PE1_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD2_Pin,
  LD2_GPIO_Port
};

/**
  * (INT1_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DHCXInitParams =
{
  MX_GPIO_PA8_Init,
  INT1_DHCX_EXTI_IRQn, /*!< NOT USED */
  INT1_DHCX_Pin,
  INT1_DHCX_GPIO_Port
};

/**
  * (INT2_DHCX) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_DHCXInitParams =
{
  MX_GPIO_PE11_Init,
  INT2_DHCX_EXTI_IRQn, /*!< NOT USED. Must be INT2_DHCX_EXTI_IRQn */
  INT2_DHCX_Pin,
  INT2_DHCX_GPIO_Port
};

/**
  * (INT1_DLPC) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_DLPCInitParams =
{
  MX_GPIO_PB1_Init,
  INT1_DLPC_EXTI_IRQn, /*!< NOT USED */
  INT1_DLPC_Pin,
  INT1_DLPC_GPIO_Port
};

/**
  * (INT2_DLPC) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_DLPCInitParams =
{
  MX_GPIO_PC2_Init,
  INT2_DLPC_EXTI_IRQn, /*!< NOT USED. Must be INT2_DHCX_EXTI_IRQn */
  INT2_DLPC_Pin,
  INT2_DLPC_GPIO_Port
};

/**
  * (DRDY_MDC) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_DRDY_MDCInitParams =
{
  MX_GPIO_PC3_Init,
  DRDY_MDC_EXTI_IRQn, /*!< NOT USED. Must be INT2_DHCX_EXTI_IRQn */
  DRDY_MDC_Pin,
  DRDY_MDC_GPIO_Port
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_HS,
  .p_mx_init_f = MX_USB_OTG_HS_PCD_Init,
  .irq_n = OTG_HS_IRQn
};

