/**
  ******************************************************************************
  * @file    mx.c
  * @author  SRA - GPM
  *
  *
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "spi.h"
#include "i2c.h"
#include "mdf.h"
#include "adc.h"
#include "gpdma.h"
#include "usart.h"
#include "tim.h"
#include "gpio.h"
#include "usb_otg.h"

/**
  * (USER_BUTTON 1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_SW1InitParams =
{
  MX_GPIO_PC13_Init,
  SW1_EXTI_IRQn,
  SW1_Pin,
  SW1_GPIO_Port
};

/**
  * (LED1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED1InitParams =
{
  MX_GPIO_PF6_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED1_Pin,
  LED1_GPIO_Port
};

/**
  * (LED2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED2InitParams =
{
  MX_GPIO_PH11_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED2_Pin,
  LED2_GPIO_Port
};


/**
  * (LED3) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LED3InitParams =
{
  MX_GPIO_PH12_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED3_Pin,
  LED3_GPIO_Port
};

/**
  * (ACC_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_ACC_INT2InitParams =
{
  MX_GPIO_PF15_Init,
  ACC_INT2_EXTI_IRQn,
  ACC_INT2_Pin,
  ACC_INT2_GPIO_Port
};

/**
  * PI7 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_SPI_SEN_CS_AInitParams =
{
  MX_GPIO_PI7_Init,
  UsageFault_IRQn, /*!< NOT USED */
  SPI_SEN_CS_A_Pin,
  SPI_SEN_CS_A_GPIO_Port
};

/**
  * (IMU_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_IMU_INT1InitParams =
{
  MX_GPIO_PA4_Init,
  IMU_INT1_EXTI_IRQn,
  IMU_INT1_Pin,
  IMU_INT1_GPIO_Port
};

/**
  * (DIL_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT1_EXTERNALInitParams =
{
  MX_GPIO_PG2_Init,
  DIL_INT1_EXTI_IRQn,
  DIL_INT1_Pin,
  DIL_INT1_GPIO_Port
};

/**
  * (DIL_INT2) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_INT2_EXTERNALInitParams =
{
  MX_GPIO_PG6_Init,
  DIL_INT2_EXTI_IRQn,
  DIL_INT2_Pin,
  DIL_INT2_GPIO_Port
};

/**
  * (DIL_CS) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_CS_EXTERNALInitParams =
{
  MX_GPIO_PG1_Init,
  UsageFault_IRQn, /*!< NOT USED */
  SPI_DUT_CS_Pin,
  SPI_DUT_CS_GPIO_Port
};

/**
  * PI5 Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_SPI_SEN_CS_GInitParams =
{
  MX_GPIO_PI5_Init,
  UsageFault_IRQn, /*!< NOT USED */
  SPI_SEN_CS_G_Pin,
  SPI_SEN_CS_G_GPIO_Port
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_FS,
  .p_mx_init_f = MX_USB_OTG_FS_PCD_Init,
  .irq_n = OTG_FS_IRQn
};

/**
  * SPI2 initialization parameters.
  */
const MX_SPIParams_t MX_SPI2InitParams =
{
  .p_mx_init_f = MX_SPI2_Init,
  .p_spi_handle = &hspi2,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_dma_rx_irq_n = GPDMA1_Channel0_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel1_IRQn
};

/**
  * SPI2 initialization parameters.
  */
const MX_SPIParams_t MX_SPI3InitParams =
{
  .p_mx_init_f = MX_SPI3_Init,
  .p_spi_handle = &hspi3,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_dma_rx_irq_n = GPDMA1_Channel6_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel7_IRQn
};

const MX_SPIParams_t MX_SPI3_20MHzInitParams =
{
  .p_mx_init_f = MX_SPI3_20MHz_Init,
  .p_spi_handle = &hspi3,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .spi_dma_rx_irq_n = GPDMA1_Channel6_IRQn,
  .spi_dma_tx_irq_n = GPDMA1_Channel7_IRQn
};

/**
  * I2C1 initialization parameters.
  */
const MX_I2CParams_t MX_I2C1InitParams =
{
  .p_mx_init_f = MX_I2C1_Init,
  .p_i2c_handle = &hi2c1,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i2c_er_irq_n = I2C1_ER_IRQn,
  .i2c_ev_irq_n = I2C1_EV_IRQn,
  .i2c_dma_rx_irq_n = GPDMA1_Channel2_IRQn,
  .i2c_dma_tx_irq_n = GPDMA1_Channel3_IRQn
};

/**
  * I2C3 initialization parameters.
  */
const MX_I2CParams_t MX_I2C3InitParams =
{
  .p_mx_init_f = MX_I2C3_Init,
  .p_i2c_handle = &hi2c3,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i2c_er_irq_n = I2C3_ER_IRQn,
  .i2c_ev_irq_n = I2C3_EV_IRQn,
  .i2c_dma_rx_irq_n = GPDMA1_Channel8_IRQn,
  .i2c_dma_tx_irq_n = GPDMA1_Channel4_IRQn
};
#if 0
/**
  * MDF initialization parameters.
  */
const MX_MDFParams_t MX_MDF1InitParams =
{
  .p_mdf_config = &MdfFilterConfig0,
  .p_mdf = &MdfHandle0,
  .p_mdf_dma_config = &MdfDmaConfig,
  .irq_n = GPDMA1_Channel4_IRQn,
  .p_mx_init_f = MX_MDF1_Init,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom
};
#endif
/**
  * ADF initialization parameters.
  */
const MX_MDFParams_t MX_ADF1InitParams =
{
  .p_mdf_config = &AdfFilterConfig0,
  .p_mdf = &AdfHandle0,
  .p_mdf_dma_config = &AdfDmaConfig,
  .irq_n = GPDMA1_Channel5_IRQn,
  .p_mx_init_f = MX_ADF1_Init,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom
};

/**
  * ADC1 initialization parameters.
  */
const MX_ADCParams_t MX_ADC1InitParams =
{
  .p_adc = &hadc1,
  .p_mx_init_f = MX_ADC1_Init
};

/**
  * ADC4 initialization parameters.
  */
const MX_ADCParams_t MX_ADC4InitParams =
{
  .p_adc = &hadc4,
  .p_mx_init_f = MX_ADC4_Init
};

/**
  * TIM3 initialization parameters.
  */
const MX_TIMParams_t MX_TIM3InitParams =
{
  .p_mx_init_f = MX_TIM3_Init,
  .p_tim = &htim3,
  .irq_n = TIM3_IRQn
};


/**
  * TIM4 initialization parameters.
  */
const MX_TIMParams_t MX_TIM4InitParams =
{
  .p_mx_init_f = MX_TIM4_Init,
  .p_tim = &htim4,
  .irq_n = TIM4_IRQn
};

/**
  * TIM5 initialization parameters.
  */
const MX_TIMParams_t MX_TIM5InitParams =
{
  .p_mx_init_f = MX_TIM5_Init,
  .p_tim = &htim5,
  .irq_n = TIM5_IRQn
};
