/**
  ******************************************************************************
  * @file    mx.c
  * @author  SRA - GPM
  *
  *
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "tim.h"
#include "i3c.h"
#include "gpio.h"
#include "gpdma.h"
#include "usb.h"


/**
  * TIM3 initialization parameters (12MHz CLK_IN output for VL53L9).
  */
const MX_TIMParams_t MX_TIM3InitParams =
{
  .p_mx_init_f = MX_TIM3_Init,
  .p_tim = &htim3,
  .irq_n = TIM3_IRQn
};

/**
  * TIM7 initialization parameters.
  */
const MX_TIMParams_t MX_TIM7InitParams =
{
  .p_mx_init_f = MX_TIM7_Init,
  .p_tim = &htim7,
  .irq_n = TIM7_IRQn
};

/**
  * I3C1 initialization parameters.
  */
const MX_I3CParams_t MX_I3C1InitParams =
{
  .p_mx_init_f = MX_I3C1_Init,
  .p_i3c_handle = &hi3c1,
  .p_mx_dma_init_f = MX_GPDMA1_InitCustom,
  .i3c_er_irq_n = I3C1_ER_IRQn,
  .i3c_ev_irq_n = I3C1_EV_IRQn,
  .i3c_dma_tc_irq_n = GPDMA1_Channel0_IRQn,
  .i3c_dma_rx_irq_n = GPDMA1_Channel2_IRQn,
  .i3c_dma_tx_irq_n = GPDMA1_Channel1_IRQn
};

/**
  * LED Red Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDRedInitParams =
{
  MX_GPIO_PG4_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_RED_Pin,
  LED_RED_GPIO_Port
};

/**
  * LED Green Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDGreenInitParams =
{
  MX_GPIO_PB0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_GREEN_Pin,
  LED_GREEN_GPIO_Port
};

/**
  * LED Blue Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LEDYellowInitParams =
{
  MX_GPIO_PF4_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LED_YELLOW_Pin,
  LED_YELLOW_GPIO_Port
};

/**
  * (VL53L9_INT) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_VL53L9_INTInitParams =
{
  MX_GPIO_PB7_Init,
  VL53L9_INT_EXTI_IRQn,
  VL53L9_INT_Pin,
  VL53L9_INT_GPIO_Port
};

/**
  * (VL53L9_XSHUT) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_VL53L9_XSHUTInitParams =
{
  MX_GPIO_PB6_Init,
  UsageFault_IRQn, /*!< NOT USED */
  VL53L9_XSHUT_Pin,
  VL53L9_XSHUT_GPIO_Port
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_DRD_FS,
  .p_mx_init_f = MX_USB_PCD_Init,
  .irq_n = USB_DRD_FS_IRQn
};

