/**
  ******************************************************************************
  * @file    mx.c
  * @author  SRA - GPM
  *
  *
  *
  * @brief Project peripherals configuration files.
  *
  * This files defines the peripherals configuration parameters that can be used
  * in the Low Level API of an eLooM driver - IDrvInit(). It creates a link
  * between the initialization code generated by CubeMX (see the .ioc file
  * in the tools folder) and the eLooM framework.
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ******************************************************************************
  */

#include "mx.h"
#include "tim.h"
#include "i2c.h"
#include "gpio.h"
#include "dma.h"
#include "usb_otg.h"


/**
  * TIM7 initialization parameters.
  */
const MX_TIMParams_t MX_TIM7InitParams =
{
  .p_mx_init_f = MX_TIM7_Init,
  .p_tim = &htim7,
  .irq_n = TIM7_IRQn
};

/**
  * I2C1 initialization parameters.
  */
const MX_I2CParams_t MX_I2C1InitParams =
{
  .p_mx_init_f = MX_I2C1_Init,
  .p_i2c_handle = &hi2c1,
  .p_mx_dma_init_f = MX_DMA_InitCustom,
  .i2c_er_irq_n = I2C1_ER_IRQn,
  .i2c_ev_irq_n = I2C1_EV_IRQn,
  .i2c_dma_rx_irq_n = DMA1_Stream0_IRQn,
  .i2c_dma_tx_irq_n = DMA1_Stream1_IRQn
};

/**
  * LED1 (Green) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD1InitParams =
{
  MX_GPIO_PB0_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD1_Pin,
  LD1_GPIO_Port
};

/**
  * LED3 (Red) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD3InitParams =
{
  MX_GPIO_PB14_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD3_Pin,
  LD3_GPIO_Port
};

/**
  * LED2 (Yellow) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LD2InitParams =
{
  MX_GPIO_PE1_Init,
  UsageFault_IRQn, /*!< NOT USED */
  LD2_Pin,
  LD2_GPIO_Port
};

/**
  * (LIS2MDL_DRDY) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LIS2MDL_DRDYInitParams =
{
  MX_GPIO_PC3_Init,
  LIS2MDL_DRDY_O_EXTI_IRQn,
  LIS2MDL_DRDY_O_Pin,
  LIS2MDL_DRDY_O_GPIO_Port
};

/**
  * (LIS2DUXS12_INT) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LIS2DUXS12_INTInitParams =
{
  MX_GPIO_PB1_Init,
  LIS2DUXS12_INT_O_EXTI_IRQn,
  LIS2DUXS12_INT_O_Pin,
  LIS2DUXS12_INT_O_GPIO_Port
};

/**
  * (LSM6DSV16X_INT1) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LSM6DSV16X_INT1InitParams =
{
  MX_GPIO_PE11_Init,
  LSM6DSV16X_INT1_EXTI_IRQn,
  LSM6DSV16X_INT1_Pin,
  LSM6DSV16X_INT1_GPIO_Port
};

/**
  * (LPS22DF_INT) Initialization parameters.
  */
const MX_GPIOParams_t MX_GPIO_LPS22DF_INTInitParams =
{
  MX_GPIO_PA8_Init,
  LPS22DF_INT_O_EXTI_IRQn,
  LPS22DF_INT_O_Pin,
  LPS22DF_INT_O_GPIO_Port
};

const MX_PCDParams_t MX_PCDInitParams =
{
  .p_pcd = &hpcd_USB_OTG_HS,
  .p_mx_init_f = MX_USB_OTG_HS_PCD_Init,
  .irq_n = OTG_HS_IRQn
};

