/**
  ********************************************************************************
  * @file    AI_SC_DPU.h
  * @author  STMicroelectronics - AIS - MCD Team
  * @version 1.0.0
  * @date    Oct 25, 2022
  *
  * @brief
  *
  * <ADD_FILE_DESCRIPTION>
  *
  ********************************************************************************
  * @attention
  *
  * Copyright (c) 2021 STMicroelectronics
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file in
  * the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  ********************************************************************************
  */
#ifndef DPU_INC_AI_SC_DPU_H_
#define DPU_INC_AI_SC_DPU_H_

#ifdef __cplusplus
extern "C" {
#endif


#include "ADPU2.h"
#include "ADPU2_vtbl.h"
#include "services/IAI_Network.h"
#include "services/IAI_Network_vtbl.h"


/**
  * Create  type name for _AI_SC_DPU.
  */
typedef struct _AI_SC_DPU AI_SC_DPU_t;

/**
  *  AI_SC_DPU internal structure.
  */
struct _AI_SC_DPU
{
  /**
    * Base class object.
    */
  ADPU2_t super;

  /* DPU variables should be added here. */

  /**
    * Network If. This interface is used to operate a network generated by X-CUBE-AI.
    */
  IAI_Network_t *p_network;

};


/* Public API declaration */
/**************************/

/**
  * Allocate an instance of _AI_SC_DPU in the framework heap.
  *
  * @return a pointer to the generic object ::IDPU2 if success,
  *         or NULL if out of memory error occurs.
  */
IDPU2_t *AI_SC_DPU_Alloc(void);

/**
  * Allocate an instance of AI_SC_DPU_t in a memory block specified by the application.
  * The size of the memory block must be greater or equal to sizeof(AI_DPU_t).
  * This allocator allows the application to avoid the dynamic allocation.
  *
  * \code
  * AI_SC_DPU_t dpu;
  * AI_SC_DPU_StaticAlloc(&dpu);
  * \endcode
  *
  * @param p_mem_block [IN] specify a memory block allocated by the application.
  *        The size of the memory block must be greater or equal to sizeof(AI_DPU_t).
  * @return a pointer to the generic object ::IDPU2_t if success,
  * or NULL if out of memory error occurs.
  */
IDPU2_t *AI_SC_DPU_StaticAlloc(void *p_mem_block);

/**
  * Initialize the DPU.
  * @TODO: this function is a placeholder.
  *        A developer must add DPU specific initialization parameters.
  *
  * @param _this [IN] specifies an object instance.
  * @param p_network [IN] specifies an interface of a network generated by X-CUBE-AI
  * @return SYS_NO_ERROR_CODE if success, an application specific error code otherwise.
  */
sys_error_code_t AI_SC_DPU_Init(AI_SC_DPU_t *_this, IAI_Network_t *p_network);


/* Inline functions definition */
/*******************************/


#ifdef __cplusplus
}
#endif

#endif /* DPU_INC_AI_SC_DPU_H_ */
